#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Determine if the application is in maintenance mode...
$isMaintenanceMode = file_exists(__DIR__.'/storage/framework/maintenance.php');

if ($isMaintenanceMode) {
    require __DIR__.'/storage/framework/maintenance.php';
}

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
